name: Deploy pages

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
    - name: Run blog build tool
      run: dotnet run --project ./src/Nemonuri.BlogTools/Nemonuri.BlogTools.csproj
    - name: Configure pages
      uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: './artifact/_site'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment